apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.git.url }}
    targetRevision: {{ .Values.git.branch }}
    path: apps/echo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true