apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: ingress
    repoURL: https://charts.konghq.com
    targetRevision: 0.14.0
    helm:
      releaseName: kong
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
     - ServerSideApply=true