apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    # Name of the tunnel you want to run
    tunnel: stoddinet
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: echo.neilvana.com
        service: http://kong-gateway-proxy.kong.svc.cluster.local
      - hostname: argo.neilvana.com
        service: http://argo-server.argo.svc.cluster.local
      - service: http_status:503
